# Generated by Django 4.2.3 on 2023-07-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptme',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
