# Generated by Django 4.2.3 on 2023-07-14 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_adoptme_description_alter_adoptme_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptme',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
