# Generated by Django 4.2.3 on 2023-07-14 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_adoptme_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptme',
            old_name='description',
            new_name='Descripcion',
        ),
        migrations.RenameField(
            model_name='adoptme',
            old_name='imagen',
            new_name='Imagen',
        ),
        migrations.RenameField(
            model_name='adoptme',
            old_name='title',
            new_name='Nombre',
        ),
        migrations.RenameField(
            model_name='adoptme',
            old_name='breed',
            new_name='Raza',
        ),
    ]
