# Generated by Django 4.2.3 on 2023-07-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_nombre_recomendaciones_titulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendaciones',
            old_name='descripcion',
            new_name='mensaje',
        ),
        migrations.AddField(
            model_name='adoptme',
            name='Genero',
            field=models.IntegerField(choices=[[0, 'Macho'], [1, 'Hembra']], default=1),
        ),
        migrations.AlterField(
            model_name='recomendaciones',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
