# Generated by Django 4.2.3 on 2023-07-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_adoptme_genero_adoptme_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptme',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
