# Generated by Django 4.2.3 on 2023-07-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_adoptme_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptme',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='adoptme',
            name='Imagen',
            field=models.ImageField(null=True, upload_to='productos/'),
        ),
    ]
