# Generated by Django 4.2.3 on 2023-07-18 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_alter_adoptme_options_alter_adoptme_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptme',
            name='Descripcion',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='adoptme',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
    ]
