# Generated by Django 4.2.3 on 2023-07-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_adoptme_descripcion_alter_adoptme_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptme',
            name='redsocial',
            field=models.TextField(max_length=20, null=True),
        ),
    ]
