# Generated by Django 4.2.3 on 2023-07-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_adoptme_redsocial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adoptme',
            old_name='redsocial',
            new_name='RedSocial',
        ),
    ]
