# Generated by Django 4.2.3 on 2023-07-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_rename_redsocial_adoptme_redsocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptme',
            name='RedSocial',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
