# Generated by Django 4.2.3 on 2023-07-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_alter_adoptme_redsocial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recomendaciones',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='recomendaciones',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
